[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[[plugins]]
  package = "@netlify/plugin-lambda"

[functions]
  directory = "netlify/functions"
  
[functions."api/*"]
  included_files = ["netlify/functions/**", "models/**", "db/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
