[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


# sample dev block in the toml
# note: each of these fields are optional and should only be used if you need an override
[dev]
  targetPort = 8000 # The port for your application server, framework, or site generator
  port = 8888 # The port that the Netlify Dev will be accessible on
 